// Events - Type Exports
export {
  // Schemas
  domainEventSchema,
  aggregateTypeEnum,
  eventTypeEnum,
  createDomainEventSchema,
  patientCreatedPayloadSchema,
  appointmentCreatedPayloadSchema,
  appointmentStatusChangedPayloadSchema,
  appointmentPriorityChangedPayloadSchema,
  appointmentConfirmedPayloadSchema,
  appointmentRescheduledPayloadSchema,
  appointmentAttendedPayloadSchema,
  appointmentNoShowPayloadSchema,
  appointmentCancelledPayloadSchema,
  decisionCreatedPayloadSchema,
  decisionResolvedPayloadSchema,
  decisionApprovedPayloadSchema,
  decisionRejectedPayloadSchema,
  // Types
  type AggregateType,
  type EventType,
  type DomainEvent,
  type CreateDomainEventInput,
  type PatientCreatedPayload,
  type AppointmentCreatedPayload,
  type AppointmentStatusChangedPayload,
  type AppointmentPriorityChangedPayload,
  type AppointmentConfirmedPayload,
  type AppointmentRescheduledPayload,
  type AppointmentAttendedPayload,
  type AppointmentNoShowPayload,
  type AppointmentCancelledPayload,
  type DecisionCreatedPayload,
  type DecisionResolvedPayload,
  type DecisionApprovedPayload,
  type DecisionRejectedPayload,
} from './schemas'

// Domain Event Interfaces
export {
  type BaseDomainEvent,
  type PatientCreatedEvent,
  type PatientUpdatedEvent,
  type PatientDeletedEvent,
  type AppointmentCreatedEvent,
  type AppointmentStatusChangedEvent,
  type AppointmentPriorityChangedEvent,
  type AppointmentConfirmedEvent,
  type AppointmentRescheduledEvent,
  type AppointmentAttendedEvent,
  type AppointmentNoShowEvent,
  type AppointmentCancelledEvent,
  type DecisionCreatedEvent,
  type DecisionResolvedEvent,
  type DecisionApprovedEvent,
  type DecisionRejectedEvent,
  type TypedDomainEvent,
  type DomainEventHandler,
  type EventPublisherPort,
  type EventDispatcher,
} from './domainEvents'
